### PR TITLE
docs: editor-service schema version 5

### PR DESCRIPTION
**Pull request by dsherret**
This schema version introduces parallel messages, cancellable formatting, and range formatting support.

Before this is merged and worked on, the following tasks should be implemented:

- [x] Implement cancellation support and range formatting for process plugins (follow #479) - I have started working on this implementation and it is a big change so will take some time.
- [x] Switch to using tokio in the cli (#480)
- [x] ~~Look into and implement cancellation support and range formatting for Wasm plugins.~~ Will do this later

This won't be happening for a while, but FYI @ryan-rushton. Would appreciate your feedback in case you think there's anything missing or any features you think would be useful. I will help with the dprint-intellij changes when we get to that point.

Todo:

- [x] Align with the design in #486

### CODE REVIEW

**Comment by ryan-rushton** [comment]
I will have a think about any other useful features but cancellation and range formatting are definitely at the top of my list for wanted features in the intellij plugin.

**Comment by ryan-rushton** [comment]
@dsherret are we actually introducing range formatting? I was pointed to [this](https://github.com/dprint/dprint/issues/464#issuecomment-1030885956) conversation the other day.

**Comment by dsherret** [comment]
Yes, I decided to add it after that feedback because I’m breaking all the interfaces right now in order to improve them. It’s going to have it in the platform at least, but not necessarily implemented by the existing plugins. I already implemented it in the new process plugin interface (along with cancellation). Will add it to the editor interface here next, then lastly to the Wasm plugin interface.

**Comment by dsherret** [comment]
Implementation is in https://github.com/dprint/dprint/pull/505

**Pull request merged**
