### PR TITLE
perf: faster glob walking

### LINKED ISSUE #407: Improve globbing performance
As noted in @joscha's message [here](https://github.com/dprint/dprint/pull/405#issuecomment-908840165) the globbing performance has degraded between v0.15.1 and v0.16.2. In that scenario it went from 10s to 25s on a repo with 30K matches.

There are definitely ways to make this faster again and maybe even moreso than before.

### PR DESCRIPTION
**Pull request by dsherret**
This change uses one thread to do the `fs::read_dir` calls and another to do the glob matching. It seems to be faster on my machine, but I'm not sure how it compares to old versions of dprint.

Closes #407.

### CODE REVIEW

**Comment by dsherret** [comment]
@joscha would you be able to do me a favour and test out this PR compared to the current version and old version that was faster whenever you get a chance. I hope it will be faster than the old version now in your scenario (otherwise I will investigate more).

```bash
git clone https://github.com/dprint/dprint -b fast-glob-walking --single-branch dprint_glob_walking
cd dprint_glob_walking
cargo build --release
```

Binary will be at `./target/release/dprint`.

I think you will need to run the binary a few times to get an accurate picture of globbing speed.

**Comment by joscha** [comment]
Ah, missed this one. I opened it and then forgot the marked email. Let me check it now!

**Comment by dsherret** [comment]
@joscha that's no problem! It's released in 0.17.1 so you should be able to just download the binary now.

**Comment by joscha** [comment]
0.17.1 hones in at around 2s total:
```
❯ time /Users/joscha/Downloads/dprint\ 3  output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm > out
/Users/joscha/Downloads/dprint\ 3 output-file-paths --plugins    > out  1.24s user 1.63s system 131% cpu 2.175 total

~/work/canva joscha/ts-reformat-all
❯ time /Users/joscha/Downloads/dprint\ 3  output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm > out
/Users/joscha/Downloads/dprint\ 3 output-file-paths --plugins    > out  1.13s user 1.49s system 130% cpu 2.010 total

~/work/canva joscha/ts-reformat-all
❯ time /Users/joscha/Downloads/dprint\ 3  output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm > out
/Users/joscha/Downloads/dprint\ 3 output-file-paths --plugins    > out  1.08s user 1.45s system 131% cpu 1.919 total
```

The version before is consistently slower usually 2X:

```
~/work/canva joscha/ts-reformat-all
❯ time DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out
[DEBUG] Arguments passed on to original dprint binary: output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm
DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out  1.79s user 1.57s system 89% cpu 3.734 total

~/work/canva joscha/ts-reformat-all
❯ time DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out
[DEBUG] Arguments passed on to original dprint binary: output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm
DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out  1.88s user 1.64s system 98% cpu 3.564 total

~/work/canva joscha/ts-reformat-all
❯ time DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out
[DEBUG] Arguments passed on to original dprint binary: output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm
DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out  1.92s user 2.14s system 98% cpu 4.119 total

~/work/canva joscha/ts-reformat-all
❯ time DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out
[DEBUG] Arguments passed on to original dprint binary: output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm
DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out  2.13s user 2.51s system 98% cpu 4.690 total
```

good work!

**Comment by dsherret** [comment]
Oh wow, so in 0.15.1 it was 10s then 0.16.1 it was 25s and now 2s? Is this the same test as here https://github.com/dprint/dprint/pull/405#issuecomment-908840165 ?

**Comment by joscha** [comment]
> Oh wow, so in 0.15.1 it was 10s then 0.16.1 it was 25s and now 2s?

Yes. Although the very first invocation of the CLI after context switching is always a bit slower:

```
[DEBUG] Arguments passed on to original dprint binary: output-file-paths --plugins /nix/store/m29l55mx5qs720366ylrmaqzwbahvcfw-markdown.wasm /nix/store/pjb51pdynffypw65v9zs0glazkidw68w-typescript.wasm /nix/store/yzdjx618s1gv0i4iflsb4br7hkmq8kdp-json.wasm
DPRINT_NIX_WRAPPER_DEBUG=true tools/dprint/dprint output-file-paths > out  1.90s user 2.18s system 43% cpu 9.308 total
```

not 100% sure why this is - some sort of FS caching possibly. Every invocation after is consistently fast.

> Is this the same test as here [#405 (comment)](https://github.com/dprint/dprint/pull/405#issuecomment-908840165) ?

Same codebase, but not the same commit. Slightly different globs and probably a few more files since that test.

**Comment by dsherret** [comment]
@joscha awesome! Glad to know this is so much faster.

I think perhaps looking at [`dir_entry.file_type()`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_type) instead of [`dir_entry.metadata()`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.metadata) must have led to the biggest performance increase (or perhaps dropping the walkdir dependency, which uses metadata).

> not 100% sure why this is - some sort of FS caching possibly. Every invocation after is consistently fast.

Yes, I think it's caching. I've noticed the same behaviour so I run it a few times to get a better idea.

**Comment by joscha** [comment]
Unfortunately I found a regression that is very likely related to this: https://github.com/dprint/dprint/issues/416 - hopefully we can fix that up easily with the new setup.

**Pull request merged**
