### PR TITLE
chore: add dependabot to automate dependencies

### PR DESCRIPTION
**Pull request by chenrui333**
add dependabot support to automate the dependencies (as well as security dependency patches)

### CODE REVIEW

**Comment by dsherret** [comment]
Dependabot is my greatest enemy 😅. Causes so much noise.

@chenrui333 do you know if there is a way to limit this to critical security issues? This would be great if so!

**Comment by chenrui333** [comment]
> Dependabot is my greatest enemy 😅. Causes so much noise.
> 
> @chenrui333 do you know if there is a way to limit this to critical security issues? This would be great if so!

we can make it monthly update or even limit the PRs. I am using it for OSS projects as well as my company projects, my experience on it is good so far. :)

**Comment by dsherret** [comment]
Ok, let’s go for one month. That’s not too bad 🙂

Thanks!

**Comment by dsherret** [comment]
Thanks @chenrui333!

**Comment by dsherret** [comment]
Sorry, I reverted this right after it opened all the major version bumps PRs. I'd rather upgrade dependencies on my own time.

**Pull request merged**
