### PR TITLE
feat: musl libc support

### PR DESCRIPTION
**Pull request by XDream8**
Since i don't know js a lot i could not update [deployment](https://github.com/dprint/dprint/tree/main/deployment)

Now you should just update plugins json files. [for example](https://plugins.dprint.dev/prettier-0.15.0.json)

[I gave you write access to my fork so you can improve the code if you see anything wrong](https://github.com/XDream8/dprint/invitations).

### CODE REVIEW

**Comment by XDream8** [comment]
Depends on:
- [dprint/automation#1](https://github.com/dprint/automation/pull/1)
- [dprint/dprint-plugin-prettier#40](https://github.com/dprint/dprint-plugin-prettier/pull/40)

**Comment by XDream8** [comment]
Some other plugins require us to add support for musl in ci workflows.

I will create pr for some of them later today

**Comment by XDream8** [comment]
- [dprint/dprint-plugin-exec](https://github.com/dprint/dprint-plugin-exec/pull/18)
- [dprint/dprint-plugin-rustfmt](https://github.com/dprint/dprint-plugin-rustfmt/pull/10)

**Comment by dsherret** [comment]
Sorry for my delay, I've been busy with other things the past week (especially with the deno minor release coming up this week). I'm planning on getting this through sometime over the next two weeks and will have some time over Christmas. Thanks for opening all the PRs though!

**Comment by dsherret** [comment]
@XDream8 this is looking good now. Could you do me a favour and just make sure this musl build works with the latest `dprint-plugin-exec plugin? https://github.com/dprint/dprint-plugin-exec

Then additionally, could you run this code on your musl system and tell me the output (requires Node.js installed):

```js
// main.js
var os = require("os");
function getIsMusl() {
  // code adapted from https://github.com/lovell/detect-libc
  // Copyright Apache 2.0 license, the detect-libc maintainers
  try {
    if (os.platform() !== "linux") {
      return false;
    }
    return isProcessReportMusl() || isConfMusl();
  } catch (err) {
    // just in case
    console.warn("Error checking if musl.", err);
  }

  function isProcessReportMusl() {
    if (!process.report) {
      return false;
    }
    const report = process.report.getReport();
    if (!report || !(report.sharedObjects instanceof Array)) {
      return false;
    }
    return report.sharedObjects.some((o) =>
      o.includes("libc.musl-") || o.includes("ld-musl-")
    );
  }

  function isConfMusl() {
    const output = getCommandOutput();
    const [_, ldd1] = output.split(/[\r\n]+/);
    return ldd1 && ldd1.includes("musl");
  }

  function getCommandOutput() {
    try {
      const command =
        "getconf GNU_LIBC_VERSION 2>&1 || true; ldd --version 2>&1 || true";
      return require("child_process").execSync(command, { encoding: "utf8" });
    } catch (_err) {
      return "";
    }
  }
}
console.log(getIsMusl());
```

Put in `main.js` file then run:

```
node main.js
```

After that I think we'll be good to land this. Thanks so much for the help and contributing this feature once again!

**Comment by XDream8** [comment]
dprint compiled ok and dprint-plugin-exec works.
I tested that js code and it returned true.
Everything seems to work fine.

Your code implementation is much better than mine since it does not iterate through a directory every time dprint is run

**Comment by dsherret** [comment]
Awesome! Thanks so much for testing it out. I'll merge this and do a release soon.

**Pull request merged**
