### PR TITLE
chore: upgrade swc_ecma_parser to 0.23.1

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/5848

**Comment by dsherret** [comment]
Don't worry about failing CI. I'll look into it later.

I'll do a release right now.

**Comment by bartlomieju** [comment]
> Don't worry about failing CI. I'll look into it later.
> 
> I'll do a release right now.

You're very fast! Thanks!

**Comment by dsherret** [comment]
@bartlomieju the benefits of being unemployed 😂

When you integrate this into Deno, I hope my new change here won't cause any issues... I needed to add this to get it to build a WASM file:

https://github.com/dprint/dprint/pull/226/files#diff-de5fc3a341ac9a0271a2c06a627657bfR13

This is now published in 0.19.0.

**Comment by bartlomieju** [comment]
@dsherret upgrade done without any troubles :)

**Pull request merged**
